"""add reply_on_accept

Revision ID: dc065bc6d97a
Revises: 0006_push_outbox
Create Date: 2026-05-21 23:04:55.071805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc065bc6d97a'
down_revision: Union[str, None] = '0006_push_outbox'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_max_user_id_key', 'admins', type_='unique')
    op.drop_index('ix_admins_max_user_id', table_name='admins')
    op.create_index(op.f('ix_admins_max_user_id'), 'admins', ['max_user_id'], unique=True)
    op.drop_constraint('form_submissions_idempotency_key_key', 'form_submissions', type_='unique')
    op.drop_index('ix_form_submissions_idempotency_key', table_name='form_submissions')
    op.create_index(op.f('ix_form_submissions_idempotency_key'), 'form_submissions', ['idempotency_key'], unique=True)
    op.add_column('form_templates', sa.Column('reply_on_accept', sa.Text(), nullable=True))
    op.drop_constraint('messages_external_id_key', 'messages', type_='unique')
    op.drop_index('ix_messages_external_id', table_name='messages')
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=True)
    op.drop_index('ix_push_outbox_pending', table_name='push_outbox', postgresql_where='(sent_at IS NULL)')
    op.drop_index('ix_users_email_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_first_name_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_last_name_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_patronymic_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_phone_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_study_group_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_user_id_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_username_trgm', table_name='users', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username_trgm', 'users', ['username'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_user_id_trgm', 'users', ['user_id'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_study_group_trgm', 'users', ['study_group'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_phone_trgm', 'users', ['phone'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_patronymic_trgm', 'users', ['patronymic'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_last_name_trgm', 'users', ['last_name'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_first_name_trgm', 'users', ['first_name'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_email_trgm', 'users', ['email'], unique=False, postgresql_using='gin')
    op.create_index('ix_push_outbox_pending', 'push_outbox', ['next_retry_at'], unique=False, postgresql_where='(sent_at IS NULL)')
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.create_index('ix_messages_external_id', 'messages', ['external_id'], unique=False)
    op.create_unique_constraint('messages_external_id_key', 'messages', ['external_id'])
    op.drop_column('form_templates', 'reply_on_accept')
    op.drop_index(op.f('ix_form_submissions_idempotency_key'), table_name='form_submissions')
    op.create_index('ix_form_submissions_idempotency_key', 'form_submissions', ['idempotency_key'], unique=False)
    op.create_unique_constraint('form_submissions_idempotency_key_key', 'form_submissions', ['idempotency_key'])
    op.drop_index(op.f('ix_admins_max_user_id'), table_name='admins')
    op.create_index('ix_admins_max_user_id', 'admins', ['max_user_id'], unique=False)
    op.create_unique_constraint('admins_max_user_id_key', 'admins', ['max_user_id'])
    # ### end Alembic commands ###
